### ISSUE TITLE
Build a distribution with a pre-installed Docker

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/linux-image-templates#2]
So we can use Tart instead of Docker for Desktop.

**Comment by fkorotkov** [comment]
We probably need a more sophesicated VM image with more stuff preinstalled. Similar to [what we have](https://github.com/cirruslabs/vm-images/blob/master/googlecompute/ubuntu_images.json) for docker_builder on Cirrus CI. Eventually we want to use this image to power Linux Cirrus Runners.

**Comment by edigaryev** [comment]
> We probably need a more sophesicated VM image with more stuff preinstalled. Similar to [what we have](https://github.com/cirruslabs/vm-images/blob/master/googlecompute/ubuntu_images.json) for docker_builder on Cirrus CI. Eventually we want to use this image to power Linux Cirrus Runners.

Do we want to include this in the main VM image (e.g. `ghcr.io/cirruslabs/ubuntu:22.04`), or in a separate one?

**Comment by fkorotkov** [comment]
Probably a separate one based on the ubuntu one?
